/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;

class AppTest {

    //TASK 2 tests
    @Test
    public void testTask2() {
        List<String> input = Arrays.asList("hello", "world", "a", "", "testing", "123", "ab");
        List<String> expected = Arrays.asList("ello", "orld", "", "esting", "23", "b");

        List<String> result = Task2(input);

        assertEquals(expected, result);
    }//TASK 2 tests

    @Test
    public void testTask2EmptyList() {
        List<String> input = Collections.emptyList();
        List<String> expected = Collections.emptyList();

        List<String> result = Task2(input);

        assertEquals(expected, result);
    }//TASK 2 tests


    //write a test for Task6 method
    @Test void task6RoundsUpElementsToNearestHundred() {
        // Arrange
        App classBeingTested = new App();
        List<Integer> data = Arrays.asList(0,1,101,99,200,151,999);
        List<Integer> expected = Arrays.asList(100,100,100,100,200,200,1000);
        // Act
        List<Integer> result = classBeingTested.Task6(data);
        // Assert
        assertEquals(expected, result);
        }
}
